import { theme } from "../theme";
import { ThemeProvider } from "@mui/material";

export const metadata = {
  title: "이음",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
