import { theme } from "../theme";
import { ThemeProvider } from "@mui/material";
import { gmarket } from "../font/font";

export const metadata = {
  title: "이음",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>
          <div className={`${gmarket.variable}`}>{children}</div>
        </body>
      </ThemeProvider>
    </html>
  );
}
