import { gmarket } from "../font/font";
import ThemeContextProvider from "../components/ThemeContext";

export const metadata = {
  title: "이음",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/favicon/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicon/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicon/favicon-16x16.png"
      />
      <link rel="manifest" href="/site.webmanifest" />
      <ThemeContextProvider>
        <body>
          <div className={`${gmarket.variable}`}>{children}</div>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
